In [1]:
import numpy as np

In [2]:
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [5]:
c = np.array([2, 3, 4, 5, 6, 2]).reshape(2, 3)
c

array([[2, 3, 4],
       [5, 6, 2]])

In [12]:
d = np.array([2, 3, 4, 5, 6, 7, 8, 9]).reshape(2, 2, 2)
d

array([[[2, 3],
        [4, 5]],

       [[6, 7],
        [8, 9]]])

In [13]:
e = np.array([1, 2, 3, 4, 5, 6])
print(e.sum())
print(e.min())
print(e.max())
print(e.mean())

21
1
6
3.5


In [16]:
print(np.zeros(5))
print(np.linspace(0, 6, 10))
print(np.random.rand(3))
print(np.random.randint(1,1000))
print(np.arange(25))

[0. 0. 0. 0. 0.]
[0.         0.66666667 1.33333333 2.         2.66666667 3.33333333
 4.         4.66666667 5.33333333 6.        ]
[0.36721958 0.52031579 0.89560104]
610
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
